import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const importsPageSource = readFileSync(
    new URL('../../resources/js/pages/imports/Index.vue', import.meta.url),
    'utf8',
);

const importsMessagesSource = readFileSync(
    new URL('../../resources/js/i18n/messages/imports.ts', import.meta.url),
    'utf8',
);

const importsShowSource = readFileSync(
    new URL('../../resources/js/pages/imports/Show.vue', import.meta.url),
    'utf8',
);

test('imports file picker only advertises xlsx in the primary ui flow', () => {
    assert.match(
        importsPageSource,
        /accept="\.xlsx,application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet"/,
    );
    assert.doesNotMatch(importsPageSource, /\.csv,text\/csv,\.txt/);
});

test('imports copy presents the official xlsx template as the primary flow', () => {
    assert.match(
        importsMessagesSource,
        /template XLSX ufficiale generato dall'app/,
    );
    assert.match(importsMessagesSource, /Usa una sola colonna Conto/);
    assert.match(
        importsMessagesSource,
        /official XLSX template generated by the app/,
    );
    assert.match(importsMessagesSource, /Use a single Account column/);
    assert.match(
        importsMessagesSource,
        /Conto di destinazione serve solo per i giroconti/,
    );
    assert.match(
        importsMessagesSource,
        /Destination account is only for transfer rows/,
    );
    assert.doesNotMatch(importsMessagesSource, /File XLSX o CSV/);
    assert.doesNotMatch(importsMessagesSource, /XLSX or CSV file/);
});

test('imports detail row layout protects long detail and category values', () => {
    assert.match(
        importsShowSource,
        /grid gap-4 xl:grid-cols-\[minmax\(0,1fr\)_auto]/,
    );
    assert.ok(
        importsShowSource.includes(
            'sm:grid-cols-2 lg:grid-cols-[5rem_7rem_7rem_9rem_minmax(0,1.35fr)_minmax(0,1fr)]',
        ),
    );
    assert.match(importsShowSource, /min-w-0 sm:col-span-2 lg:col-span-1/);
    assert.match(importsShowSource, /class="mt-1 truncate text-sm/);
    assert.match(importsShowSource, /xl:w-\[22rem] xl:items-end/);
});

test('imports detail feedback uses semantic tones instead of error red for ready rows', () => {
    assert.match(importsShowSource, /const feedbackToneClasses: Record/);
    assert.match(importsShowSource, /function rowFeedbackTone/);
    assert.match(importsShowSource, /return row\.status_tone;/);
    assert.match(importsShowSource, /tone === 'success'/);
    assert.match(importsShowSource, /<component/);
    assert.match(importsShowSource, /:is="rowFeedbackIcon\(row\)"/);
});

test('import row review dialog uses hierarchical category and tracked item selectors plus the mobile amount editor', () => {
    const reviewDialogSource = readFileSync(
        new URL(
            '../../resources/js/components/imports/ImportRowReviewDialog.vue',
            import.meta.url,
        ),
        'utf8',
    );

    assert.match(reviewDialogSource, /import MobileAmountInput/);
    assert.match(reviewDialogSource, /import MobileSearchableSelect/);
    assert.match(
        reviewDialogSource,
        /referenceOptions: ImportReferenceOption\[]/,
    );
    assert.match(reviewDialogSource, /<MobileAmountInput/);
    assert.match(reviewDialogSource, /<MobileSearchableSelect/);
    assert.match(reviewDialogSource, /hierarchical/);
    assert.match(reviewDialogSource, /creatable/);
    assert.match(reviewDialogSource, /createTrackedItemFromContext/);
    assert.match(reviewDialogSource, /tracked_item_uuid/);
    assert.match(reviewDialogSource, /category_uuid/);
    assert.match(reviewDialogSource, /shouldShowCategoryField/);
    assert.match(reviewDialogSource, /category\.group_type/);
    assert.match(reviewDialogSource, /isTrackedItemCompatible/);
    assert.match(reviewDialogSource, /referenceHelper/);
});

test('imports history keeps pagination controls and a resilient summary row layout', () => {
    assert.match(
        importsPageSource,
        /imports\.index\.listSection\.paginationLabel/,
    );
    assert.match(importsPageSource, /role="navigation"/);
    assert.match(importsPageSource, /min-w-0 flex-1 space-y-3/);
    assert.match(importsPageSource, /class="truncate text-base font-semibold/);
    assert.match(importsPageSource, /class="min-w-0 truncate"/);
    assert.match(importsPageSource, /xl:w-\[25rem] xl:grid-cols-2/);
});
