<?php

return [
    'default' => 'EUR',

    'supported' => [
        'EUR' => [
            'code' => 'EUR',
            'symbol' => '€',
            'name' => 'Euro',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'it-IT',
        ],
        'USD' => [
            'code' => 'USD',
            'symbol' => '$',
            'name' => 'US Dollar',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'en-US',
        ],
        'GBP' => [
            'code' => 'GBP',
            'symbol' => '£',
            'name' => 'British Pound',
            'minor_unit' => 2,
            'locale' => 'en-GB',
            'symbol_position' => 'prefix',
        ],
        'CHF' => [
            'code' => 'CHF',
            'symbol' => 'CHF',
            'name' => 'Swiss Franc',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'de-CH',
        ],
        'JPY' => [
            'code' => 'JPY',
            'symbol' => '¥',
            'name' => 'Japanese Yen',
            'minor_unit' => 0,
            'symbol_position' => 'prefix',
            'locale' => 'ja-JP',
        ],
        'CAD' => [
            'code' => 'CAD',
            'symbol' => 'C$',
            'name' => 'Canadian Dollar',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'en-CA',
        ],
        'AUD' => [
            'code' => 'AUD',
            'symbol' => 'A$',
            'name' => 'Australian Dollar',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'en-AU',
        ],
        'SEK' => [
            'code' => 'SEK',
            'symbol' => 'kr',
            'name' => 'Swedish Krona',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'sv-SE',
        ],
        'NOK' => [
            'code' => 'NOK',
            'symbol' => 'kr',
            'name' => 'Norwegian Krone',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'nb-NO',
        ],
        'DKK' => [
            'code' => 'DKK',
            'symbol' => 'kr',
            'name' => 'Danish Krone',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'da-DK',
        ],
        'PLN' => [
            'code' => 'PLN',
            'symbol' => 'zl',
            'name' => 'Polish Zloty',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'pl-PL',
        ],
        'CZK' => [
            'code' => 'CZK',
            'symbol' => 'Kc',
            'name' => 'Czech Koruna',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'cs-CZ',
        ],
        'HUF' => [
            'code' => 'HUF',
            'symbol' => 'Ft',
            'name' => 'Hungarian Forint',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'hu-HU',
        ],
        'RON' => [
            'code' => 'RON',
            'symbol' => 'lei',
            'name' => 'Romanian Leu',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'ro-RO',
        ],
        'BGN' => [
            'code' => 'BGN',
            'symbol' => 'lv',
            'name' => 'Bulgarian Lev',
            'minor_unit' => 2,
            'symbol_position' => 'suffix',
            'locale' => 'bg-BG',
        ],
        'TRY' => [
            'code' => 'TRY',
            'symbol' => '₺',
            'name' => 'Turkish Lira',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'tr-TR',
        ],
        'CNY' => [
            'code' => 'CNY',
            'symbol' => '¥',
            'name' => 'Chinese Yuan',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'zh-CN',
        ],
        'HKD' => [
            'code' => 'HKD',
            'symbol' => 'HK$',
            'name' => 'Hong Kong Dollar',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'zh-HK',
        ],
        'SGD' => [
            'code' => 'SGD',
            'symbol' => 'S$',
            'name' => 'Singapore Dollar',
            'minor_unit' => 2,
            'symbol_position' => 'prefix',
            'locale' => 'en-SG',
        ],
    ],
    'providers' => [
        'frankfurter' => [
            'base_url' => env('FRANKFURTER_BASE_URL', 'https://api.frankfurter.dev/v2'),
            'timeout' => (int) env('FRANKFURTER_TIMEOUT_SECONDS', 10),
        ],
        'fawaz' => [
            'api_version' => 'v1',
            'timeout' => (int) env('FAWAZ_TIMEOUT_SECONDS', 10),
            'jsdelivr_base_url' => env(
                'FAWAZ_JSDELIVR_BASE_URL',
                'https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api'
            ),
            'pages_dev_template' => env(
                'FAWAZ_PAGES_DEV_TEMPLATE',
                'https://%s.currency-api.pages.dev'
            ),
        ],
    ],
    'sync' => [
        'base_currency_code' => env('CURRENCY_RATES_SYNC_BASE', 'EUR'),
        'core_currency_codes' => [
            'EUR',
            'USD',
            'GBP',
            'CHF',
        ],
        'quote_currency_codes' => [
            'USD',
            'GBP',
            'CHF',
            'JPY',
            'CAD',
            'AUD',
            'SEK',
            'NOK',
            'DKK',
            'PLN',
            'CZK',
            'HUF',
            'RON',
            'BGN',
            'TRY',
            'CNY',
            'HKD',
            'SGD',
        ],
        'daily_at' => env('CURRENCY_RATES_SYNC_DAILY_AT', '18:00'),
    ],
    'alerts' => [
        'telegram' => [
            'enabled' => env('CURRENCY_RATES_SYNC_ALERTS_TELEGRAM_ENABLED', false),
            'bot_token' => env('CURRENCY_RATES_SYNC_ALERTS_TELEGRAM_BOT_TOKEN'),
            'chat_id' => env('CURRENCY_RATES_SYNC_ALERTS_TELEGRAM_CHAT_ID'),
        ],
    ],
    'format_locales' => [
        'it-IT' => 'Italia (1.234,56)',
        'en-GB' => 'United Kingdom (1,234.56)',
        'en-US' => 'United States (1,234.56)',
    ],
    'format_preferences' => [
        'thousands_separators' => [
            'dot' => '.',
            'comma' => ',',
            'space' => 'space',
        ],
        'decimal_separators' => [
            'comma' => ',',
            'dot' => '.',
        ],
        'date_formats' => [
            'DD/MM/YYYY',
            'MM/DD/YYYY',
            'YYYY-MM-DD',
            'D MMM YYYY',
            'MMM D, YYYY',
        ],
    ],
];
